export const LOAD_FIXED_VALUE_ENTRIES_REQUEST = 'LOAD_FIXED_VALUE_ENTRIES_REQUEST';
export const LOAD_FIXED_VALUE_ENTRIES_SUCCESS = 'LOAD_FIXED_VALUE_ENTRIES_SUCCESS';
export const LOAD_FIXED_VALUE_ENTRIES_ERROR = 'LOAD_FIXED_VALUE_ENTRIES_ERROR';


